"""Auto-generated migration

Revision ID: cdfadf8cd891
Revises: dff228bc7c23
Create Date: 2023-09-22 18:56:09.726853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdfadf8cd891'
down_revision = 'dff228bc7c23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
