"""Auto-generated migration

Revision ID: dff228bc7c23
Revises: d4867f3a4c0a
Create Date: 2023-09-20 23:56:03.216498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dff228bc7c23'
down_revision = 'd4867f3a4c0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('department', sa.String(), nullable=True))
    op.add_column('user', sa.Column('school', sa.String(), nullable=True))
    op.add_column('user', sa.Column('is_staff', sa.Boolean(), nullable=True))
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_user_department'), 'user', ['department'], unique=False)
    op.create_index(op.f('ix_user_school'), 'user', ['school'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_school'), table_name='user')
    op.drop_index(op.f('ix_user_department'), table_name='user')
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('user', 'is_staff')
    op.drop_column('user', 'school')
    op.drop_column('user', 'department')
    # ### end Alembic commands ###
